<?php

namespace Database\Seeders;

use App\Models\Flight;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class flightSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    use RefreshDatabase;
    public function run(): void
    {
        DB::table('flights')->insert([
            [
                'plane_id' => 1,
                'flight_number' => 'RY1023',
                'departure_airport' => 'Dublin Airport (DUB)',
                'arrival_airport' => 'London Stansted (STN)',
                'departure_time' => '2025-04-01 08:30:00',
                'arrival_time' => '2025-04-01 09:45:00',
                'available_seats' => 150,
                'price' => 49.99,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plane_id' => 2,
                'flight_number' => 'EZ2085',
                'departure_airport' => 'Paris Charles de Gaulle (CDG)',
                'arrival_airport' => 'Berlin Brandenburg (BER)',
                'departure_time' => '2025-04-02 14:20:00',
                'arrival_time' => '2025-04-02 16:00:00',
                'available_seats' => 180,
                'price' => 59.99,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plane_id' => 3,
                'flight_number' => 'WZ3301',
                'departure_airport' => 'Madrid Barajas (MAD)',
                'arrival_airport' => 'Lisbon Airport (LIS)',
                'departure_time' => '2025-04-03 10:00:00',
                'arrival_time' => '2025-04-03 10:55:00',
                'available_seats' => 160,
                'price' => 45.50,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plane_id' => 4,
                'flight_number' => 'LH7842',
                'departure_airport' => 'Frankfurt Airport (FRA)',
                'arrival_airport' => 'Amsterdam Schiphol (AMS)',
                'departure_time' => '2025-04-04 12:30:00',
                'arrival_time' => '2025-04-04 14:00:00',
                'available_seats' => 190,
                'price' => 67.25,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plane_id' => 5,
                'flight_number' => 'AF5123',
                'departure_airport' => 'Rome Fiumicino (FCO)',
                'arrival_airport' => 'Munich Airport (MUC)',
                'departure_time' => '2025-04-05 07:45:00',
                'arrival_time' => '2025-04-05 09:20:00',
                'available_seats' => 175,
                'price' => 55.99,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plane_id' => 6,
                'flight_number' => 'KLM4405',
                'departure_airport' => 'Barcelona El Prat (BCN)',
                'arrival_airport' => 'London Heathrow (LHR)',
                'departure_time' => '2025-04-06 15:15:00',
                'arrival_time' => '2025-04-06 17:00:00',
                'available_seats' => 165,
                'price' => 72.75,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plane_id' => 7,
                'flight_number' => 'BA2228',
                'departure_airport' => 'Vienna International (VIE)',
                'arrival_airport' => 'Copenhagen Airport (CPH)',
                'departure_time' => '2025-04-07 13:50:00',
                'arrival_time' => '2025-04-07 15:20:00',
                'available_seats' => 155,
                'price' => 64.50,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plane_id' => 1,
                'flight_number' => 'FR5011',
                'departure_airport' => 'Oslo Gardermoen (OSL)',
                'arrival_airport' => 'Stockholm Arlanda (ARN)',
                'departure_time' => '2025-04-08 09:30:00',
                'arrival_time' => '2025-04-08 10:45:00',
                'available_seats' => 140,
                'price' => 50.00,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plane_id' => 2,
                'flight_number' => 'TP7854',
                'departure_airport' => 'Brussels Airport (BRU)',
                'arrival_airport' => 'Zurich Airport (ZRH)',
                'departure_time' => '2025-04-09 18:00:00',
                'arrival_time' => '2025-04-09 19:20:00',
                'available_seats' => 170,
                'price' => 63.75,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plane_id' => 3,
                'flight_number' => 'AY3302',
                'departure_airport' => 'Helsinki Vantaa (HEL)',
                'arrival_airport' => 'Berlin Brandenburg (BER)',
                'departure_time' => '2025-04-10 20:10:00',
                'arrival_time' => '2025-04-10 21:40:00',
                'available_seats' => 160,
                'price' => 69.99,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plane_id' => 4,
                'flight_number' => 'VY9841',
                'departure_airport' => 'Warsaw Chopin (WAW)',
                'arrival_airport' => 'Prague Vaclav Havel (PRG)',
                'departure_time' => '2025-04-11 07:30:00',
                'arrival_time' => '2025-04-11 08:50:00',
                'available_seats' => 155,
                'price' => 58.99,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plane_id' => 5,
                'flight_number' => 'LX6743',
                'departure_airport' => 'Athens International (ATH)',
                'arrival_airport' => 'Rome Fiumicino (FCO)',
                'departure_time' => '2025-04-12 12:00:00',
                'arrival_time' => '2025-04-12 13:50:00',
                'available_seats' => 180,
                'price' => 76.50,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plane_id' => 6,
                'flight_number' => 'AZ9982',
                'departure_airport' => 'Milan Malpensa (MXP)',
                'arrival_airport' => 'Madrid Barajas (MAD)',
                'departure_time' => '2025-04-13 16:45:00',
                'arrival_time' => '2025-04-13 19:10:00',
                'available_seats' => 165,
                'price' => 80.25,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'plane_id' => 7,
                'flight_number' => 'TK1107',
                'departure_airport' => 'Istanbul Airport (IST)',
                'arrival_airport' => 'Paris Charles de Gaulle (CDG)',
                'departure_time' => '2025-04-14 22:30:00',
                'arrival_time' => '2025-04-15 01:10:00',
                'available_seats' => 190,
                'price' => 99.99,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        
    }
}
